### ISSUE TITLE
images for README

### ISSUE THREAD

**Issue by mattlub** [jema28/mc-airbnb-css#5]
@jema28 upload the image of the design please!

Colours:
<img width="256" alt="colours" src="https://user-images.githubusercontent.com/16781318/48892918-cfba9380-ee47-11e8-8c9b-2481912c05fe.png">

**Comment by jema28** [comment]
![mobile](https://user-images.githubusercontent.com/25960351/48894868-76089800-ee4c-11e8-8125-70f977b0902b.png)
